
/**
 * @roxi/routify 2.18.8
 * File generated Sat Mar 30 2024 02:18:52 GMT+0530 (India Standard Time)
 */

export const __version = "2.18.8"
export const __timestamp = "2024-03-29T20:48:52.926Z"

//buildRoutes
import { buildClientTree } from "@roxi/routify/runtime/buildRoutes"

//imports


//options
export const options = {}

//tree
export const _tree = {
  "name": "_layout",
  "filepath": "/_layout.svelte",
  "root": true,
  "ownMeta": {},
  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/_layout.svelte",
  "children": [
    {
      "isFile": true,
      "isDir": false,
      "file": "_fallback.svelte",
      "filepath": "/_fallback.svelte",
      "name": "_fallback",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/_fallback.svelte",
      "importPath": "../src/pages/_fallback.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": true,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/_fallback",
      "id": "__fallback",
      "component": () => import('../src/pages/_fallback.svelte').then(m => m.default)
    },
    {
      "isFile": false,
      "isDir": true,
      "file": "components",
      "filepath": "/components",
      "name": "components",
      "ext": "",
      "badExt": false,
      "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components",
      "children": [
        {
          "isFile": true,
          "isDir": false,
          "file": "academicNews.svelte",
          "filepath": "/components/academicNews.svelte",
          "name": "academicNews",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components/academicNews.svelte",
          "importPath": "../src/pages/components/academicNews.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/academicNews",
          "id": "_components_academicNews",
          "component": () => import('../src/pages/components/academicNews.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "communityForum.svelte",
          "filepath": "/components/communityForum.svelte",
          "name": "communityForum",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components/communityForum.svelte",
          "importPath": "../src/pages/components/communityForum.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/communityForum",
          "id": "_components_communityForum",
          "component": () => import('../src/pages/components/communityForum.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "contact.svelte",
          "filepath": "/components/contact.svelte",
          "name": "contact",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components/contact.svelte",
          "importPath": "../src/pages/components/contact.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/contact",
          "id": "_components_contact",
          "component": () => import('../src/pages/components/contact.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Footer.svelte",
          "filepath": "/components/Footer.svelte",
          "name": "Footer",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components/Footer.svelte",
          "importPath": "../src/pages/components/Footer.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Footer",
          "id": "_components_Footer",
          "component": () => import('../src/pages/components/Footer.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "landingNavBar.svelte",
          "filepath": "/components/landingNavBar.svelte",
          "name": "landingNavBar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components/landingNavBar.svelte",
          "importPath": "../src/pages/components/landingNavBar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/landingNavBar",
          "id": "_components_landingNavBar",
          "component": () => import('../src/pages/components/landingNavBar.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "login.svelte",
          "filepath": "/components/login.svelte",
          "name": "login",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components/login.svelte",
          "importPath": "../src/pages/components/login.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/login",
          "id": "_components_login",
          "component": () => import('../src/pages/components/login.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "navbar.svelte",
          "filepath": "/components/navbar.svelte",
          "name": "navbar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components/navbar.svelte",
          "importPath": "../src/pages/components/navbar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/navbar",
          "id": "_components_navbar",
          "component": () => import('../src/pages/components/navbar.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "recommendations.svelte",
          "filepath": "/components/recommendations.svelte",
          "name": "recommendations",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components/recommendations.svelte",
          "importPath": "../src/pages/components/recommendations.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/recommendations",
          "id": "_components_recommendations",
          "component": () => import('../src/pages/components/recommendations.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "signup.svelte",
          "filepath": "/components/signup.svelte",
          "name": "signup",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components/signup.svelte",
          "importPath": "../src/pages/components/signup.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/signup",
          "id": "_components_signup",
          "component": () => import('../src/pages/components/signup.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "userDashboard.svelte",
          "filepath": "/components/userDashboard.svelte",
          "name": "userDashboard",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/components/userDashboard.svelte",
          "importPath": "../src/pages/components/userDashboard.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/userDashboard",
          "id": "_components_userDashboard",
          "component": () => import('../src/pages/components/userDashboard.svelte').then(m => m.default)
        }
      ],
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/components"
    },
    {
      "isFile": false,
      "isDir": true,
      "file": "courses",
      "filepath": "/courses",
      "name": "courses",
      "ext": "",
      "badExt": false,
      "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses",
      "children": [
        {
          "isFile": false,
          "isDir": true,
          "file": "educationlevel",
          "filepath": "/courses/educationlevel",
          "name": "educationlevel",
          "ext": "",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel",
          "children": [
            {
              "isFile": false,
              "isDir": true,
              "file": "diploma",
              "filepath": "/courses/educationlevel/diploma",
              "name": "diploma",
              "ext": "",
              "badExt": false,
              "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/diploma",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/courses/educationlevel/diploma/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/diploma/index.svelte",
                  "importPath": "../src/pages/courses/educationlevel/diploma/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/diploma/index",
                  "id": "_courses_educationlevel_diploma_index",
                  "component": () => import('../src/pages/courses/educationlevel/diploma/index.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/courses/educationlevel/diploma"
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "doctoral",
              "filepath": "/courses/educationlevel/doctoral",
              "name": "doctoral",
              "ext": "",
              "badExt": false,
              "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/doctoral",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "doctoralsub.svelte",
                  "filepath": "/courses/educationlevel/doctoral/doctoralsub.svelte",
                  "name": "doctoralsub",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/doctoral/doctoralsub.svelte",
                  "importPath": "../src/pages/courses/educationlevel/doctoral/doctoralsub.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/doctoral/doctoralsub",
                  "id": "_courses_educationlevel_doctoral_doctoralsub",
                  "component": () => import('../src/pages/courses/educationlevel/doctoral/doctoralsub.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/courses/educationlevel/doctoral/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/doctoral/index.svelte",
                  "importPath": "../src/pages/courses/educationlevel/doctoral/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/doctoral/index",
                  "id": "_courses_educationlevel_doctoral_index",
                  "component": () => import('../src/pages/courses/educationlevel/doctoral/index.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/courses/educationlevel/doctoral"
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "highersecondary",
              "filepath": "/courses/educationlevel/highersecondary",
              "name": "highersecondary",
              "ext": "",
              "badExt": false,
              "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/highersecondary",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "highersecondarysub.svelte",
                  "filepath": "/courses/educationlevel/highersecondary/highersecondarysub.svelte",
                  "name": "highersecondarysub",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/highersecondary/highersecondarysub.svelte",
                  "importPath": "../src/pages/courses/educationlevel/highersecondary/highersecondarysub.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/highersecondary/highersecondarysub",
                  "id": "_courses_educationlevel_highersecondary_highersecondarysub",
                  "component": () => import('../src/pages/courses/educationlevel/highersecondary/highersecondarysub.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/courses/educationlevel/highersecondary/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/highersecondary/index.svelte",
                  "importPath": "../src/pages/courses/educationlevel/highersecondary/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/highersecondary/index",
                  "id": "_courses_educationlevel_highersecondary_index",
                  "component": () => import('../src/pages/courses/educationlevel/highersecondary/index.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/courses/educationlevel/highersecondary"
            },
            {
              "isFile": true,
              "isDir": false,
              "file": "index.svelte",
              "filepath": "/courses/educationlevel/index.svelte",
              "name": "index",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/index.svelte",
              "importPath": "../src/pages/courses/educationlevel/index.svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": true,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/courses/educationlevel/index",
              "id": "_courses_educationlevel_index",
              "component": () => import('../src/pages/courses/educationlevel/index.svelte').then(m => m.default)
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "mphil",
              "filepath": "/courses/educationlevel/mphil",
              "name": "mphil",
              "ext": "",
              "badExt": false,
              "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/mphil",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/courses/educationlevel/mphil/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/mphil/index.svelte",
                  "importPath": "../src/pages/courses/educationlevel/mphil/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/mphil/index",
                  "id": "_courses_educationlevel_mphil_index",
                  "component": () => import('../src/pages/courses/educationlevel/mphil/index.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "mphilsub.svelte",
                  "filepath": "/courses/educationlevel/mphil/mphilsub.svelte",
                  "name": "mphilsub",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/mphil/mphilsub.svelte",
                  "importPath": "../src/pages/courses/educationlevel/mphil/mphilsub.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/mphil/mphilsub",
                  "id": "_courses_educationlevel_mphil_mphilsub",
                  "component": () => import('../src/pages/courses/educationlevel/mphil/mphilsub.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/courses/educationlevel/mphil"
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "postdoctoral",
              "filepath": "/courses/educationlevel/postdoctoral",
              "name": "postdoctoral",
              "ext": "",
              "badExt": false,
              "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/postdoctoral",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/courses/educationlevel/postdoctoral/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/postdoctoral/index.svelte",
                  "importPath": "../src/pages/courses/educationlevel/postdoctoral/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/postdoctoral/index",
                  "id": "_courses_educationlevel_postdoctoral_index",
                  "component": () => import('../src/pages/courses/educationlevel/postdoctoral/index.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "postdoctoralsub.svelte",
                  "filepath": "/courses/educationlevel/postdoctoral/postdoctoralsub.svelte",
                  "name": "postdoctoralsub",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/postdoctoral/postdoctoralsub.svelte",
                  "importPath": "../src/pages/courses/educationlevel/postdoctoral/postdoctoralsub.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/postdoctoral/postdoctoralsub",
                  "id": "_courses_educationlevel_postdoctoral_postdoctoralsub",
                  "component": () => import('../src/pages/courses/educationlevel/postdoctoral/postdoctoralsub.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/courses/educationlevel/postdoctoral"
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "postgraduate",
              "filepath": "/courses/educationlevel/postgraduate",
              "name": "postgraduate",
              "ext": "",
              "badExt": false,
              "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/postgraduate",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/courses/educationlevel/postgraduate/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/postgraduate/index.svelte",
                  "importPath": "../src/pages/courses/educationlevel/postgraduate/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/postgraduate/index",
                  "id": "_courses_educationlevel_postgraduate_index",
                  "component": () => import('../src/pages/courses/educationlevel/postgraduate/index.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "postgraduatesub.svelte",
                  "filepath": "/courses/educationlevel/postgraduate/postgraduatesub.svelte",
                  "name": "postgraduatesub",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/postgraduate/postgraduatesub.svelte",
                  "importPath": "../src/pages/courses/educationlevel/postgraduate/postgraduatesub.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/postgraduate/postgraduatesub",
                  "id": "_courses_educationlevel_postgraduate_postgraduatesub",
                  "component": () => import('../src/pages/courses/educationlevel/postgraduate/postgraduatesub.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/courses/educationlevel/postgraduate"
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "secondary",
              "filepath": "/courses/educationlevel/secondary",
              "name": "secondary",
              "ext": "",
              "badExt": false,
              "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/secondary",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "about.svelte",
                  "filepath": "/courses/educationlevel/secondary/about.svelte",
                  "name": "about",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/secondary/about.svelte",
                  "importPath": "../src/pages/courses/educationlevel/secondary/about.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/secondary/about",
                  "id": "_courses_educationlevel_secondary_about",
                  "component": () => import('../src/pages/courses/educationlevel/secondary/about.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/courses/educationlevel/secondary/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/secondary/index.svelte",
                  "importPath": "../src/pages/courses/educationlevel/secondary/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/secondary/index",
                  "id": "_courses_educationlevel_secondary_index",
                  "component": () => import('../src/pages/courses/educationlevel/secondary/index.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "job.svelte",
                  "filepath": "/courses/educationlevel/secondary/job.svelte",
                  "name": "job",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/secondary/job.svelte",
                  "importPath": "../src/pages/courses/educationlevel/secondary/job.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/secondary/job",
                  "id": "_courses_educationlevel_secondary_job",
                  "component": () => import('../src/pages/courses/educationlevel/secondary/job.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "major.svelte",
                  "filepath": "/courses/educationlevel/secondary/major.svelte",
                  "name": "major",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/secondary/major.svelte",
                  "importPath": "../src/pages/courses/educationlevel/secondary/major.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/secondary/major",
                  "id": "_courses_educationlevel_secondary_major",
                  "component": () => import('../src/pages/courses/educationlevel/secondary/major.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "secondarysub.svelte",
                  "filepath": "/courses/educationlevel/secondary/secondarysub.svelte",
                  "name": "secondarysub",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/secondary/secondarysub.svelte",
                  "importPath": "../src/pages/courses/educationlevel/secondary/secondarysub.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/secondary/secondarysub",
                  "id": "_courses_educationlevel_secondary_secondarysub",
                  "component": () => import('../src/pages/courses/educationlevel/secondary/secondarysub.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/courses/educationlevel/secondary"
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "teaching",
              "filepath": "/courses/educationlevel/teaching",
              "name": "teaching",
              "ext": "",
              "badExt": false,
              "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/teaching",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/courses/educationlevel/teaching/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/teaching/index.svelte",
                  "importPath": "../src/pages/courses/educationlevel/teaching/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/teaching/index",
                  "id": "_courses_educationlevel_teaching_index",
                  "component": () => import('../src/pages/courses/educationlevel/teaching/index.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "teachingsub.svelte",
                  "filepath": "/courses/educationlevel/teaching/teachingsub.svelte",
                  "name": "teachingsub",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/teaching/teachingsub.svelte",
                  "importPath": "../src/pages/courses/educationlevel/teaching/teachingsub.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/teaching/teachingsub",
                  "id": "_courses_educationlevel_teaching_teachingsub",
                  "component": () => import('../src/pages/courses/educationlevel/teaching/teachingsub.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/courses/educationlevel/teaching"
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "undergraduate",
              "filepath": "/courses/educationlevel/undergraduate",
              "name": "undergraduate",
              "ext": "",
              "badExt": false,
              "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/undergraduate",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/courses/educationlevel/undergraduate/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/undergraduate/index.svelte",
                  "importPath": "../src/pages/courses/educationlevel/undergraduate/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/undergraduate/index",
                  "id": "_courses_educationlevel_undergraduate_index",
                  "component": () => import('../src/pages/courses/educationlevel/undergraduate/index.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "undergraduatesub.svelte",
                  "filepath": "/courses/educationlevel/undergraduate/undergraduatesub.svelte",
                  "name": "undergraduatesub",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/educationlevel/undergraduate/undergraduatesub.svelte",
                  "importPath": "../src/pages/courses/educationlevel/undergraduate/undergraduatesub.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "recursive": true,
                    "preload": false,
                    "prerender": true
                  },
                  "path": "/courses/educationlevel/undergraduate/undergraduatesub",
                  "id": "_courses_educationlevel_undergraduate_undergraduatesub",
                  "component": () => import('../src/pages/courses/educationlevel/undergraduate/undergraduatesub.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/courses/educationlevel/undergraduate"
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/courses/educationlevel"
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "index.svelte",
          "filepath": "/courses/index.svelte",
          "name": "index",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/index.svelte",
          "importPath": "../src/pages/courses/index.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": true,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/courses/index",
          "id": "_courses_index",
          "component": () => import('../src/pages/courses/index.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "sample.html",
          "filepath": "/courses/sample.html",
          "name": "sample",
          "ext": "html",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/courses/sample.html",
          "importPath": "../src/pages/courses/sample.html",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/courses/sample",
          "id": "_courses_sample",
          "component": () => import('../src/pages/courses/sample.html').then(m => m.default)
        }
      ],
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/courses"
    },
    {
      "isFile": false,
      "isDir": true,
      "file": "dashboard",
      "filepath": "/dashboard",
      "name": "dashboard",
      "ext": "",
      "badExt": false,
      "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/dashboard",
      "children": [
        {
          "isFile": true,
          "isDir": false,
          "file": "index.svelte",
          "filepath": "/dashboard/index.svelte",
          "name": "index",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/dashboard/index.svelte",
          "importPath": "../src/pages/dashboard/index.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": true,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/dashboard/index",
          "id": "_dashboard_index",
          "component": () => import('../src/pages/dashboard/index.svelte').then(m => m.default)
        }
      ],
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/dashboard"
    },
    {
      "isFile": true,
      "isDir": false,
      "file": "global.svelte",
      "filepath": "/global.svelte",
      "name": "global",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/global.svelte",
      "importPath": "../src/pages/global.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": true,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/global",
      "id": "_global",
      "component": () => import('../src/pages/global.svelte').then(m => m.default)
    },
    {
      "isFile": true,
      "isDir": false,
      "file": "index.svelte",
      "filepath": "/index.svelte",
      "name": "index",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/index.svelte",
      "importPath": "../src/pages/index.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": true,
      "isFallback": false,
      "isPage": true,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/index",
      "id": "_index",
      "component": () => import('../src/pages/index.svelte').then(m => m.default)
    },
    {
      "isFile": false,
      "isDir": true,
      "file": "landingPages",
      "filepath": "/landingPages",
      "name": "landingPages",
      "ext": "",
      "badExt": false,
      "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/landingPages",
      "children": [
        {
          "isFile": true,
          "isDir": false,
          "file": "blog.svelte",
          "filepath": "/landingPages/blog.svelte",
          "name": "blog",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/landingPages/blog.svelte",
          "importPath": "../src/pages/landingPages/blog.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/landingPages/blog",
          "id": "_landingPages_blog",
          "component": () => import('../src/pages/landingPages/blog.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "discoverPage.svelte",
          "filepath": "/landingPages/discoverPage.svelte",
          "name": "discoverPage",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/landingPages/discoverPage.svelte",
          "importPath": "../src/pages/landingPages/discoverPage.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/landingPages/discoverPage",
          "id": "_landingPages_discoverPage",
          "component": () => import('../src/pages/landingPages/discoverPage.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "faq.svelte",
          "filepath": "/landingPages/faq.svelte",
          "name": "faq",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/landingPages/faq.svelte",
          "importPath": "../src/pages/landingPages/faq.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/landingPages/faq",
          "id": "_landingPages_faq",
          "component": () => import('../src/pages/landingPages/faq.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "joinUs.svelte",
          "filepath": "/landingPages/joinUs.svelte",
          "name": "joinUs",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/landingPages/joinUs.svelte",
          "importPath": "../src/pages/landingPages/joinUs.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/landingPages/joinUs",
          "id": "_landingPages_joinUs",
          "component": () => import('../src/pages/landingPages/joinUs.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "keyFeaturesPage.svelte",
          "filepath": "/landingPages/keyFeaturesPage.svelte",
          "name": "keyFeaturesPage",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/landingPages/keyFeaturesPage.svelte",
          "importPath": "../src/pages/landingPages/keyFeaturesPage.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/landingPages/keyFeaturesPage",
          "id": "_landingPages_keyFeaturesPage",
          "component": () => import('../src/pages/landingPages/keyFeaturesPage.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "knowMoreUs.svelte",
          "filepath": "/landingPages/knowMoreUs.svelte",
          "name": "knowMoreUs",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/landingPages/knowMoreUs.svelte",
          "importPath": "../src/pages/landingPages/knowMoreUs.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/landingPages/knowMoreUs",
          "id": "_landingPages_knowMoreUs",
          "component": () => import('../src/pages/landingPages/knowMoreUs.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "resourcesReview.svelte",
          "filepath": "/landingPages/resourcesReview.svelte",
          "name": "resourcesReview",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/landingPages/resourcesReview.svelte",
          "importPath": "../src/pages/landingPages/resourcesReview.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/landingPages/resourcesReview",
          "id": "_landingPages_resourcesReview",
          "component": () => import('../src/pages/landingPages/resourcesReview.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "wellcomePage.svelte",
          "filepath": "/landingPages/wellcomePage.svelte",
          "name": "wellcomePage",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/landingPages/wellcomePage.svelte",
          "importPath": "../src/pages/landingPages/wellcomePage.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/landingPages/wellcomePage",
          "id": "_landingPages_wellcomePage",
          "component": () => import('../src/pages/landingPages/wellcomePage.svelte').then(m => m.default)
        }
      ],
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/landingPages"
    },
    {
      "isFile": false,
      "isDir": true,
      "file": "template",
      "filepath": "/template",
      "name": "template",
      "ext": "",
      "badExt": false,
      "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/template",
      "children": [
        {
          "isFile": true,
          "isDir": false,
          "file": "indexdesign.svelte",
          "filepath": "/template/indexdesign.svelte",
          "name": "indexdesign",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/template/indexdesign.svelte",
          "importPath": "../src/pages/template/indexdesign.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/template/indexdesign",
          "id": "_template_indexdesign",
          "component": () => import('../src/pages/template/indexdesign.svelte').then(m => m.default)
        }
      ],
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/template"
    },
    {
      "isFile": false,
      "isDir": true,
      "file": "themes",
      "filepath": "/themes",
      "name": "themes",
      "ext": "",
      "badExt": false,
      "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/themes",
      "children": [
        {
          "isFile": true,
          "isDir": false,
          "file": "aboutdesign.svelte",
          "filepath": "/themes/aboutdesign.svelte",
          "name": "aboutdesign",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/themes/aboutdesign.svelte",
          "importPath": "../src/pages/themes/aboutdesign.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/themes/aboutdesign",
          "id": "_themes_aboutdesign",
          "component": () => import('../src/pages/themes/aboutdesign.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "buttonStyle.svelte",
          "filepath": "/themes/buttonStyle.svelte",
          "name": "buttonStyle",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/themes/buttonStyle.svelte",
          "importPath": "../src/pages/themes/buttonStyle.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/themes/buttonStyle",
          "id": "_themes_buttonStyle",
          "component": () => import('../src/pages/themes/buttonStyle.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "jobdesign.svelte",
          "filepath": "/themes/jobdesign.svelte",
          "name": "jobdesign",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/themes/jobdesign.svelte",
          "importPath": "../src/pages/themes/jobdesign.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/themes/jobdesign",
          "id": "_themes_jobdesign",
          "component": () => import('../src/pages/themes/jobdesign.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "majordesign.svelte",
          "filepath": "/themes/majordesign.svelte",
          "name": "majordesign",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/themes/majordesign.svelte",
          "importPath": "../src/pages/themes/majordesign.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/themes/majordesign",
          "id": "_themes_majordesign",
          "component": () => import('../src/pages/themes/majordesign.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Template.svelte",
          "filepath": "/themes/Template.svelte",
          "name": "Template",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "G:/miniProject/K PERIYATHAMBI 22PG101CSC009/StudyPathHubCode/web/src/pages/themes/Template.svelte",
          "importPath": "../src/pages/themes/Template.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/themes/Template",
          "id": "_themes_Template",
          "component": () => import('../src/pages/themes/Template.svelte').then(m => m.default)
        }
      ],
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/themes"
    }
  ],
  "isLayout": true,
  "isReset": false,
  "isIndex": false,
  "isFallback": false,
  "isPage": false,
  "isFile": true,
  "file": "_layout.svelte",
  "ext": "svelte",
  "badExt": false,
  "importPath": "../src/pages/_layout.svelte",
  "meta": {
    "recursive": true,
    "preload": false,
    "prerender": true
  },
  "path": "/",
  "id": "__layout",
  "component": () => import('../src/pages/_layout.svelte').then(m => m.default)
}


export const {tree, routes} = buildClientTree(_tree)

