<script>
  import Indexdesign from "../template/indexdesign.svelte";

  let nextpathData = {
    head: "What's Your Education Level",
    data: [
      {
        title: "Secondary Education",
        description: "Classes 9 and 10",
        majorlink: "/recourse/educationlevel/secondary/major",
        aboutlink: "/recourse/educationlevel/secondary/about",
        joblink: "/recourse/educationlevel/secondary/job",
        link: "/recourse/educationlevel/secondary",
      },
      {
        title: "Higher Secondary Education",
        description: "Classes 11 and 12",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/recourse/educationlevel/highersecondary",
      },
      {
        title: "Undergraduate Education",
        description: "Bachelor's Degrees in various fields",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/recourse/educationlevel/undergraduate",
      },
      {
        title: "Postgraduate Education",
        description: "Master's Degrees in various fields",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/recourse/educationlevel/postgraduate",
      },
      {
        title: "Doctoral Education",
        description: "Ph.D. (Doctor of Philosophy)",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/recourse/educationlevel/doctoral",
      },
      {
        title: "Diploma Programs",
        description: "Short-term diploma recourse in various subjects",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/recourse/educationlevel/diploma",
      },
      {
        title: "Vocational Education",
        description: "Skill-based training and education",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/vocational-education",
      },
      {
        title: "Technical Education",
        description: "Engineering and technology recourse",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/technical-education",
      },
      {
        title: "Medical Education",
        description: "MBBS, BDS, and other medical degrees",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/medical-education",
      },
      {
        title: "Legal Education",
        description: "LLB (Bachelor of Laws) and LLM (Master of Laws)",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/legal-education",
      },
      {
        title: "Management Education",
        description: "MBA (Master of Business Administration)",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/management-education",
      },
      {
        title: "Arts and Humanities Education",
        description:
          "Degrees in subjects like History, Literature, Philosophy, etc.",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/arts-humanities-education",
      },
      {
        title: "Science and Technology Education",
        description: "Degrees in science and technology fields",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/science-technology-education",
      },
      {
        title: "Commerce and Business Education",
        description: "B.Com, M.Com, and related degrees",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/commerce-business-education",
      },
      {
        title: "Education Degrees",
        description:
          "B.Ed. (Bachelor of Education) and M.Ed. (Master of Education)",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/education-degrees",
      },
      {
        title: "Agricultural Education",
        description: "Degrees in agriculture and related fields",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/agricultural-education",
      },
      {
        title: "Fine Arts and Design Education",
        description: "Degrees in fine arts and design",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/fine-arts-design-education",
      },
      {
        title: "Mass Communication and Journalism",
        description: "Journalism and media-related recourse",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/mass-communication-journalism",
      },
      {
        title: "Social Sciences Education",
        description: "Degrees in subjects like Sociology, Psychology, etc.",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/social-sciences-education",
      },
      {
        title: "Paramedical and Allied Health Sciences",
        description: "recourse in medical imaging, nursing, etc.",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/paramedical-allied-health-sciences",
      },
      {
        title: "Hotel Management and Tourism",
        description: "Degrees and diploma programs in hospitality",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/hotel-management-tourism",
      },
      {
        title: "Environmental Education",
        description:
          "Programs related to environmental science and sustainability",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/environmental-education",
      },
      {
        title: "Sports and Physical Education",
        description: "recourse in physical education and sports management",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/sports-physical-education",
      },
      {
        title: "Performing Arts Education",
        description: "Music, dance, and theater-related recourse",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/performing-arts-education",
      },
      {
        title: "Aviation and Aerospace Education",
        description: "Aerospace engineering and aviation-related recourse",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/aviation-aerospace-education",
      },
      {
        title: "Adult and Continuing Education",
        description: "Adult literacy and continuing education programs",
        majorlink: "/recourse/educationlevel/major",
        aboutlink: "/recourse/educationlevel/",
        joblink: "/recourse/educationlevel/",
        link: "/adult-continuing-education",
      },
    ],
  };
</script>

<Indexdesign {nextpathData} />